### ISSUE TITLE
Incorrect formatting in IE11, Win8.1

### ISSUE THREAD

**Issue by Simcon** [starburst1977/readium#69]
Formatting is incorrect in IE 11, Win8.1:

Chrome (correct):

![untitled picture](https://cloud.githubusercontent.com/assets/1893351/6143705/e0b0c8bc-b1c4-11e4-81b9-534b2769b645.png)

IE (mangled):

![untitled picture x](https://cloud.githubusercontent.com/assets/1893351/6143679/a6ed788c-b1c4-11e4-8716-f1ff560aedad.png)

**Comment by trizz** [comment]
It seems that IE9+ has problems with the `main` element. Luckily, the fix is pretty simple; just add the following code to your css/sass:

```css
main { display: block; }
```

**Comment by Simcon** [comment]
Confirmed this fixes the issue in IE11, Win8.1 - thanks!
