### ISSUE TITLE
Add contribute.md

### ISSUE THREAD

**Issue by sudodoki** [starburst1977/readium#72]
Please, could you add some instructions on how to compile source files into the final theme? From issues it seems like this repo had grunt & make used previously. Could you please share what you use now?

**Comment by sudodoki** [comment]
@starburst1977 could you explain why you closed this issue? Didn't see any recent commits that would fix this.

**Comment by thegusti** [comment]
@sudodoki looks like he pulled up a entirely new made theme of Readium and closed all issues related to the former version.

**Comment by starburst1977** [comment]
@sudodoki Yes, I remade the whole theme. So there is nothing to compile anymore (besides the SASS files for CSS). So I closed all issues the where entirely relate to the old version of the theme. Let me know if you still have problems.

**Comment by sudodoki** [comment]
> besides the SASS files for CSS

@starburst1977 would still appreciate one-liner that will output the result just as in current theme output.
Took me some time (because haven't worked with LESS for some time) to figure out
`lessc theme_file.less -x > theme_file.css` to work with previous theme

**Comment by starburst1977** [comment]
@sudodoki I would recommend using [Codekit](https://incident57.com/codekit/) for compiling. That's what I use, because I am no command-line-hero.
